[FEATURE]: : Implementing Forgot Password Functionality with Email OTP Fixed
SB2318/UltimateHealth pull request #91
Opened 2024-05-28 16:12 UTC by Hemu21

#### PR Description
I had implemented both forget password otp to mail and verify otp and update new password

## Issue
[Issue Link](https://github.com/SB2318/UltimateHealth/issues/60) resolve #60 

## Screenshot or Video

https://github.com/SB2318/UltimateHealth/assets/106808387/dfb5e132-b481-4388-aa0a-b8c54ed2aec5

#### Type of Change
- [x] Bug fix (change which fixes an issue)
- [x] New feature (change which adds functionality)
- [ ] Documentation update

#### Select your work-area
- [ ] Frontend
- [x] Backend
- [ ] Documentation
- [ ] Others

#### Related Issue
Please provide a link to the issue solved if applicable.

#### Add your Work Example
📷 Add a Snapshot

#### Fixes (mention the issue number which this fixes)
#closes

#### Checklist
- [x] I have updated my branch and synced it with the project's 'develop' branch before making this PR.
- [x] I have optimized the file changes.
- [x] I have added a snapshot of my work example.
- [x] I have made a PR to the project's develop branch.

#### Undertaking
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] I have checked for plagiarism and assure its authenticity.
- [x] I have read and followed the code of conduct for this repository. I understand that violation of this undertaking may have legal consequences.

- [x] I Agree

2024-05-28 16:14 UTC, Hemu21 commented
@SB2318 can you please check and merge it.

2024-05-28 19:12 UTC, SB2318 commented
@Hemu21  why security check fails?

2024-05-28 19:33 UTC, Hemu21 commented
@SB2318 for sending mail we using smtp protocol. Github bot show this type of fail for most of the backend. You can Chek the security check highlights the smtp word

2024-05-28 19:35 UTC, SB2318 commented
> @SB2318 for sending mail we using smtp protocol. Github bot show this type of fail for most of the backend. You can Chek the security check highlights the smtp word

Please fix the issue, if you need any help, please reach out.

2024-05-28 19:36 UTC, Hemu21 commented
@SB2318 it is not an issue.

2024-05-28 19:44 UTC, SB2318 commented
> @Hemu21 why security check fails?



> @SB2318 it is not an issue.

![image](https://github.com/SB2318/UltimateHealth/assets/87614560/4b1d1171-f20d-4ce2-9f0f-fcacc3bbb4ee)

Try to add the secrets in **.env** file, as he did.  Let me know if you have already done so.

2024-05-28 19:49 UTC, Hemu21 commented
@SB2318 this is env file there should be the sensitive data. While deploying you need to add your data. In my localhost I use my data for testing. While pushing code. It won't be a good practice to add secrets. If I add my mail and secrets password. What if someone use that data. I hope you understand

2024-05-29 05:52 UTC, SB2318 commented on backend/routes/usersRoutes.js
> +// Forget password
When writing code, it is important to use descriptive function names that clearly convey their purpose. In this case, the suggested function names are **sendOTPForForgotPassword** and **verifyOtpForForgotPassword.** and **confirmPassword**

2024-05-29 06:00 UTC, SB2318 commented on backend/controllers/usersControllers.js
> +        console.error('Error sending email:', error);
Here, please send some details about the error, in the response body also, so that the user can identify the mistake.

2024-05-29 06:01 UTC, SB2318 commented on backend/controllers/usersControllers.js
> +        return res.status(500).json({ message: 'Error sending email.' });
Here, please send some details about the error, in the response body also, so that the user can identify the mistake.

2024-05-29 06:03 UTC, SB2318 commented on backend/controllers/usersControllers.js
> +    host: 'smtp.gmail.com',
Create a variable inside the .**env** file and store the **SMTP** host value there.

2024-05-29 06:04 UTC, SB2318 requested changes
Please make sure you have done with the requested changes and then Please raise your PR.

2024-05-29 08:43 UTC, Hemu21 commented
@SB2318  Updated. can you please check.

2024-05-29 10:03 UTC, SB2318 commented
@Hemu21  and @nishant0708 you both are working on **nodemailer**.

Please check your respective codes with a **Two-factor authentication enabled** gmail account.

We will keep a meeting in the evening regarding this.

2024-05-30 05:18 UTC, SB2318 approved these changes
Please delete **package-lock.json** file

2024-05-30 05:19 UTC, Hemu21 commented
@SB2318  ok

2024-05-30 05:21 UTC, Hemu21 commented
@SB2318  Done. can you please merge

2024-05-30 05:22 UTC, SB2318 commented
@Hemu21 

![image](https://github.com/SB2318/UltimateHealth/assets/87614560/1b7a4e08-7e4b-40d6-b3b2-2fcca0e4940a)

Can't merge

2024-05-30 05:23 UTC, Hemu21 commented
@SB2318 ok wait.

2024-05-30 05:32 UTC, Hemu21 commented
@SB2318  Now try to merge.

2024-05-30 05:34 UTC, merged

2024-05-30 05:36 UTC, nishant0708 commented
@Hemu21 I am facing same issue but I don't have package -lock.json file what should I do??

2024-05-30 05:42 UTC, Hemu21 commented
@nishant0708  Currently my code changes have been merged. We are working on the same thing. It may include a same file changes. If it rises conflict with other files you need to save you code and pull the updated develop branch. then push your code. for package-lock. You need to rectify the conflict manually. include the packagelock file.

2024-06-04 05:49 UTC, priyanshukumar397 commented
Have you checked for rate limit for this one as well @Hemu21 ?